image:
  repository: ghcr.io/madhu/python-demoapp
  pullPolicy: Always

service:
  targetPort: 5000

ingress:
  enabled: true
  host: python-demoapp.kube.madhu.io
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    enabled: true
    secretName: kube-madhu-io-cert
